const images = [
    {  url: 'animal1.jpg', category: 'animal',  },
    {  url: 'animal2.jpg', category: 'animal' },
    {  url: 'animal3.jpg', category: 'animal' },
    {  url: 'animal4.jpg', category: 'animal' },
    {  url: 'animal5.jpg', category: 'animal' },
    { url: 'animal6.jpg', category: 'animal' },
    {  url: 'animal7.jpg', category: 'animal' },
    { url: 'animal8.jpg', category: 'animal' },
    {  url: 'animal9.jpg', category: 'animal' },
    {  url: 'animal4.jpg', category: 'animal' },
    {  url: 'animal7.jpg', category: 'animal' },
    {  url: 'animal5.jpg', category: 'animal' },
    {  url: 'nature1.jpg', category: 'nature' },
    {  url: 'nature2.jpg', category: 'nature' },
    {  url: 'nature3.jpg', category: 'nature' },
    {  url: 'nature5.jpg', category: 'nature' },
    {  url: 'nature6.jpg', category: 'nature' },
    {  url: 'nature3.jpg', category: 'nature' },
    {  url: 'nature2.jpg', category: 'nature' },
    { url: 'nature1.jpg', category: 'nature' },
    {  url: 'nature2.jpg', category: 'nature' },
    { url: 'nature5.jpg', category: 'nature' },
    {  url: 'nature6.jpg', category: 'nature' },
    {  url: 'nature1.jpg', category: 'nature' },
    {  url: 'architec1.jpg', category: 'architecture' },
    {  url: 'architec2.jpg', category: 'architecture' },
    {  url: 'architec3.jpg', category: 'architecture' },
    {  url: 'architec4.jpg', category: 'architecture' },
    {  url: 'architec5.jpg', category: 'architecture' },
    {  url: 'architec6.jpg', category: 'architecture' },
    { url: 'architec7.jpg', category: 'architecture' },
    {  url: 'architec8.jpg', category: 'architecture' },
    {  url: 'architec9.jpg', category: 'architecture' },
    {  url: 'architec2.jpg', category: 'architecture' },
    {  url: 'architec3.jpg', category: 'architecture' },
    {  url: 'architec6.jpg', category: 'architecture' },
    
  ];
  
  export default images;